name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  #it is an events gives us the button in UI to run the code without push in the repository
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello world"
        shell: bash
  
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Good Bye"
        shell: bash