name: Hello world workflow

on: [ pull_request]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check array
        env:
          apps: integration_openproject
        run: |
          if [[ "$apps" == "integration_openproject" ]]; then
            echo "contains integration_openproject"
          fi

          # if [[ "$apps" != "integration_openproject" ]]; then
          #   echo "does not contain integration_openproject"
          # fi
          if [[ "$apps" == "activity" ]]; then
            echo "contains activity"
          fi
          # for app in $apps; do
          #   echo "App: $app"
          # done