name: Hello world workflow

on: [ pull_request]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Apache
        run: sudo apt update && sudo apt install -y apache2

      - name: Setup Debug Session
        uses: csexton/debugger-action@master

      - name: Set webroot
        run: |
          sudo rm -rf /var/www/html
          mkdir -p $GITHUB_WORKSPACE/public
          echo "Hello, World!" > $GITHUB_WORKSPACE/public/index.html
          sudo ln -sf $GITHUB_WORKSPACE/public /var/www/html

      - name: Start Apache
        run: sudo service apache2 start

      - name: Test
        run: curl http://localhost

      # - name: Setup Debug Session
      #   uses: csexton/debugger-action@master

      
