name: Hello world workflow

on: [ pull_request ]
  # #it is an events gives us the button in UI to run the code without push in the repository
  # workflow_dispatch:

jobs:
  _hello_:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: hello world
        run: echo "Hello world"
  
  _goodbye_:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Good Bye"

  merge:
    runs-on: ubuntu-latest
    needs: [_hello_, _goodbye_]
    steps:
      - name: merge
        run: echo "Merge"