name: Hello world workflow

on: [ pull_request ]

env:
  DAY_OF_WEEK: Monday
  BRANCH: release/2.11

jobs:
  builds:
    uses: ./.github/workflows/hello_world.yml
    secrets: inherit
    with:
      branch: $BRANCH
      nextcloud_versions: "31 32"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "$DAY_OF_WEEK"
