name: Hello world workflow

on: [ pull_request ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check env
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          BRANCH_NAME: ${{ github.ref_name }}
          BRANCH_NAMES: ${{ github.base_ref }}
        run: |
          echo "$GITHUB_ACTION_REPOSITORY"
          echo "$GITHUB_RUN_ID"
